#!/usr/bin/env python3
"""
Evaluate DNA attribution accuracy with the setting used in the paper.

This script keeps only the paper evaluation path:
  1. load the per-family MSE CSV generated by a Family_*.py script,
  2. average repeated noise samples,
  3. select the configured timesteps or sigma-derived columns,
  4. apply per-image z-score normalization across candidate models,
  5. add the configured model-wise bias and report attribution accuracy.
"""

import os

import numpy as np
import pandas as pd


TEST_CONFIGS = [
    {
        "csv_path": "DNA_SD1_results.csv",
        "n_noise": None,
        "timesteps": [],
        "bias": [],
    },
    {
        "csv_path": "DNA_SD2_results.csv",
        "n_noise": None,
        "timesteps": [],
        "bias": [],
    },
    {
        "csv_path": "DNA_SD3_results.csv",
        "n_noise": None,
        "timesteps": [],
        "bias": [],
    },
    {
        "csv_path": "DNA_SDXL_results.csv",
        "n_noise": None,
        "timesteps": [],
        "bias": [],
    },
    {
        "csv_path": "DNA_FLUX1_results.csv",
        "n_noise": None,
        "timesteps": [],
        "bias": [],
    },
    {
        "csv_path": "DNA_FLUX2_results.csv",
        "n_noise": None,
        "timesteps": [],
        "bias": [],
    },
]


def resolve_source_label(source, models):
    """Map a source-folder label to the corresponding candidate-model label."""
    if source in models:
        return source

    matches = [
        model for model in models
        if source.startswith(f"{model}-") or source.startswith(f"{model}_")
    ]
    if len(matches) == 1:
        return matches[0]

    raise ValueError(
        f"Cannot map source label '{source}' to a candidate model. "
        f"Available models: {models}"
    )


def load_mse_tensor(csv_path, n_noise):
    """Load one attribution CSV and return MSE as [images, models, steps]."""
    df = pd.read_csv(csv_path)
    step_cols = sorted(
        [col for col in df.columns if col.startswith("mse_t")],
        key=lambda col: int(col.replace("mse_t", "")),
    )
    models = sorted(df["model"].unique())

    if "noise_idx" in df.columns:
        df = df.sort_values(["source", "img_idx", "model", "noise_idx"])
        df = df.groupby(["source", "img_idx", "model"]).head(n_noise)

    # Average repeated noise samples before attribution scoring.
    df_avg = df.groupby(["source", "img_idx", "model"])[step_cols].mean().reset_index()

    records = []
    for (source, img_idx), group in df_avg.groupby(["source", "img_idx"]):
        group = group.set_index("model")
        row = {"source": source, "img_idx": img_idx}
        for model in models:
            for step_col in step_cols:
                row[f"{model}_{step_col}"] = float(group.loc[model, step_col])
        records.append(row)

    wide = pd.DataFrame(records).sort_values(["source", "img_idx"]).reset_index(drop=True)
    mse = np.zeros((len(wide), len(models), len(step_cols)), dtype=np.float32)
    for model_idx, model in enumerate(models):
        for step_idx, step_col in enumerate(step_cols):
            mse[:, model_idx, step_idx] = wide[f"{model}_{step_col}"].values

    label_to_idx = {model: idx for idx, model in enumerate(models)}
    y_true = np.array([
        label_to_idx[resolve_source_label(source, models)]
        for source in wide["source"].values
    ])
    step_values = np.array([int(col.replace("mse_t", "")) for col in step_cols])
    return mse, y_true, models, step_values


def zscore_across_models(mse):
    """Normalize each image and selected step across candidate models."""
    mean = mse.mean(axis=1, keepdims=True)
    std = mse.std(axis=1, keepdims=True)
    std = np.where(std < 1e-15, 1.0, std)
    return (mse - mean) / std


def select_step_indices(available_steps, selected_steps):
    indices = []
    for step in selected_steps:
        match = np.where(available_steps == step)[0]
        if len(match) == 0:
            raise ValueError(
                f"Step {step} is not available. Available steps: {available_steps.tolist()}"
            )
        indices.append(int(match[0]))
    return np.array(indices, dtype=np.int64)


def validate_config(config):
    missing = []
    if not config.get("csv_path"):
        missing.append("csv_path")
    if config.get("n_noise") is None:
        missing.append("n_noise")
    if not config.get("timesteps"):
        missing.append("timesteps")
    if not config.get("bias"):
        missing.append("bias")
    if missing:
        name = config.get("csv_path", "<unknown>")
        raise ValueError(f"TEST_CONFIGS entry for {name} is incomplete: {', '.join(missing)}")


def evaluate_one(config):
    validate_config(config)

    csv_path = config["csv_path"]
    n_noise = config["n_noise"]
    selected_steps = config["timesteps"]
    bias = np.array(config["bias"], dtype=np.float32)

    mse, y_true, models, available_steps = load_mse_tensor(csv_path, n_noise)
    if len(bias) != len(models):
        raise ValueError(
            f"Bias length {len(bias)} does not match the number of models {len(models)} "
            f"for {csv_path}."
        )

    # Paper setting: z-score normalized D-style scoring over selected steps.
    step_indices = select_step_indices(available_steps, selected_steps)
    scored = zscore_across_models(mse[:, :, step_indices]).mean(axis=2)

    pred_no_bias = scored.argmin(axis=1)
    pred_with_bias = (scored + bias).argmin(axis=1)

    acc_no_bias = float((pred_no_bias == y_true).mean())
    acc_with_bias = float((pred_with_bias == y_true).mean())
    return {
        "file": os.path.basename(csv_path),
        "models": models,
        "n_images": int(len(y_true)),
        "available_steps": available_steps.tolist(),
        "selected_steps": selected_steps,
        "acc_no_bias": acc_no_bias,
        "acc_with_bias": acc_with_bias,
        "pred": pred_with_bias,
        "y_true": y_true,
    }


def print_result(result):
    models = result["models"]
    y_true = result["y_true"]
    pred = result["pred"]

    print("\n" + "=" * 72)
    print(f"File: {result['file']}")
    print(f"Models: {models}")
    print(f"Images: {result['n_images']}")
    print(f"Selected steps: {result['selected_steps']}")
    print("-" * 72)
    print(f"Accuracy without bias: {result['acc_no_bias']:.4f}")
    print(f"Accuracy with bias:    {result['acc_with_bias']:.4f}")

    print("\nPer-class accuracy with bias:")
    for class_idx, model in enumerate(models):
        mask = y_true == class_idx
        correct = int((pred[mask] == class_idx).sum())
        total = int(mask.sum())
        acc = correct / total if total else 0.0
        print(f"  {model}: {acc:.4f} ({correct}/{total})")

    print("\nConfusion matrix with bias (rows=true, columns=predicted):")
    header = f"{'':>18}" + "".join(f"{model[:16]:>18}" for model in models)
    print(header)
    for row_idx, model in enumerate(models):
        row = f"{model[:16]:>18}"
        for col_idx in range(len(models)):
            row += f"{int(((y_true == row_idx) & (pred == col_idx)).sum()):>18}"
        print(row)


def main():
    results = []
    for config in TEST_CONFIGS:
        if not config.get("csv_path") or not os.path.exists(config["csv_path"]):
            print(f"[SKIP] Missing CSV: {config.get('csv_path')}")
            continue
        result = evaluate_one(config)
        print_result(result)
        results.append(result)

    if not results:
        raise SystemExit(
            "No evaluation was run. Fill TEST_CONFIGS and make sure the CSV files exist."
        )

    print("\n" + "=" * 72)
    print("Summary")
    print(f"{'file':<28} {'no bias':>10} {'with bias':>12}")
    print("-" * 52)
    for result in results:
        print(
            f"{result['file']:<28} "
            f"{result['acc_no_bias']:>10.4f} "
            f"{result['acc_with_bias']:>12.4f}"
        )


if __name__ == "__main__":
    main()
